# Permalinks

permalinks: pretty

# Setup
title: Yrsa & Rasa – open-source fonts for Latin + Gujarati
description: Yrsa & Rasa – open-source fonts for Latin + Gujarati by Rosetta
baseurl: "/yrsa-rasa/"

# About/contact
author:
  name: Rosetta
  url: https://rosettatype.com
  email: info@rosettatype.com

# Build settings
markdown: kramdown

# Articles showed on homepage
include: ['_pages']
articles:
  - title: Introducing Yrsa
    link: introducing-yrsa/
    description: "First intro to the project, the authors, and some thinking behind it"
  - title: Harmonizing Rasa Gujarati and Yrsa Latin
    link: harmonizing-rasa-gujarati-and-yrsa-latin/
    description: "Our design process when Harmonizing two different scripts"
  - title: Language support
    link: language-support/
    description: The intended language support in Latin and Gujarati scripts
  - title: About Rosetta
    link: http://github.rosettatype.com
    description: Learn more about Rosetta and its open-source projects hosted on GitHub

