# Permalinks

permalinks: pretty

# Setup
title: Yrsa & Rasa – open-source fonts for Latin + Gujarati
description: Yrsa & Rasa – open-source fonts for Latin + Gujarati by Rosetta
baseurl: "/yrsa-rasa/"

# About/contact
author:
  name: Rosetta
  url: https://rosettatype.com
  email: info@rosettatype.com

# Build settings
markdown: kramdown

# Articles showed on homepage
include: ['_pages']
articles:
  - title: 1. Introducing Yrsa
    link: introducing-yrsa/
    description: "First intro to the project, the authors, and some thinking behind it"
  - title: 2. Harmonizing Gujarati and Latin
    link: harmonizing-rasa-gujarati-and-yrsa-latin/
    description: "A hint at a design process when harmonizing two different scripts"
  - title: 3. Yrsa & Rasa released
    link: yrsa-rasa-released/
    description: "What we learned about redesigning someone else’s work"
  - title: Language support
    link: language-support/
    description: The intended language support in Latin and Gujarati scripts
  - title: About Rosetta
    link: http://github.rosettatype.com
    description: Learn more about Rosetta and its open-source projects hosted on GitHub

